# Generated by Django 4.2.7 on 2023-12-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='research_group_admins', to='users.user'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='research_group_unprivileged', to='users.user'),
        ),
    ]
