# Generated by Django 4.2.7 on 2023-12-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgroup',
            name='unprivileged',
            field=models.ManyToManyField(related_name='research_group_unprivileged', to='users.user'),
        ),
    ]
