# Generated by Django 4.2.7 on 2024-02-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.researchgroup')),
            ],
        ),
    ]
