# Generated by Django 4.2.7 on 2024-01-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalreview',
            name='private_comments',
        ),
    ]
