# Generated by Django 4.2.7 on 2024-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreview',
            name='private_comments',
            field=models.TextField(blank=True, max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='proposalreview',
            name='public_comments',
            field=models.TextField(blank=True, max_length=1600, null=True),
        ),
    ]
