# Generated by Django 4.2.7 on 2023-12-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_alter_allocation_start_alter_proposal_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='start',
        ),
        migrations.AddField(
            model_name='proposal',
            name='active',
            field=models.DateField(blank=True, null=True, verbose_name='Active Date'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
