# Generated by Django 4.2.7 on 2023-12-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('allocations', '0003_remove_allocation_expire_remove_allocation_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='submitted',
            field=models.DateField(auto_now=True, verbose_name='Submission Date'),
        ),
    ]
