# Generated by Django 4.2.7 on 2024-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('pathname', models.CharField(max_length=260)),
                ('lineno', models.IntegerField()),
                ('message', models.TextField()),
                ('func', models.CharField(blank=True, max_length=80, null=True)),
                ('sinfo', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
