# Generated by Django 4.2.7 on 2024-03-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('pathname', models.CharField(max_length=260)),
                ('lineno', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
