# Generated by Django 4.2.5 on 2023-10-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='description',
            field=models.TextField(default='', max_length=1600),
            preserve_default=False,
        ),
    ]
