# Generated by Django 4.2.5 on 2023-11-07 12:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegates', models.ManyToManyField(related_name='researchgroup_delegates', to='users.user')),
                ('members', models.ManyToManyField(to='users.user')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchgroup_pi', to='users.user')),
            ],
        ),
    ]
