name: Publish Docker Image

on:
  workflow_call:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/keystone-api

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Image

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          release_tag=${{github.ref}}
          echo "version=${release_tag#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set package version
        run: poetry version ${{ steps.version.outputs.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }},${{ env.IMAGE_NAME }}:latest
